server.port: 8000

spring:
  application:
    name: infrastructure-master
  security:
    user:
      name: service-user 
      password: password 
      roles: USER 

eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
  client:
    register-with-eureka: false
    fetch-registry: false
    server:
      wait-time-in-ms-when-sync-empty: 0
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/Infrastructure/eureka/