discovery-address: localhost:${server.port}
external-service-address: localhost:${server.port}

server:
  port: 8000
  max-http-header-size: 200000
  servlet.context-path: ${infrastructure-context-path}

spring:
  application.name: infrastructure-master
  security.user:
    name: service-user 
    password: password 
    roles: USER 

management:
  endpoints.web.exposure.include: "*" 
  endpoint.health.show-details: ALWAYS

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: ${infrastructure-context-path}/actuator/health
    status-page-url-path: http://${external-service-address}${infrastructure-context-path}/hystrix/monitor?stream=http%3A%2F%2Fservice-user%3Apassword%40localhost%3A8100%2FNexusService%2Factuator%2Fhystrix.stream&delay=1000&title=Nexus%20Service%20Monitor
    management.context-path: ${infrastructure-context-path}
    metadata-map.user:
      name: service-user
      password: password
  client:
    register-with-eureka: true
    fetch-registry: false
    server.wait-time-in-ms-when-sync-empty: 0
    service-url.defaultZone: http://service-user:password@${discovery-address}${infrastructure-context-path}/eureka/