discovery-address: localhost:8000
external-service-address: localhost:${server.port}

server:
  port: 8350
  max-http-header-size: 200000
  servlet.context-path: ${legal-context-path}
  
  tomcat:
    max-connections: 2000
    max-http-post-size: 200000
    max-threads: 50
    min-spare-threads: 10

spring:
  application.name: legal-service
  security.user:
    name: service-user 
    password: password
    roles: USER

management:
  endpoints.web.exposure.include: "*" 
  endpoint.health.show-details: ALWAYS

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: ${legal-context-path}/actuator/health
    status-page-url-path: http://${external-service-address}${legal-context-path}/actuator/info
    management.context-path: ${legal-context-path}
    metadata-map.user:
      name: service-user
      password: password
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5    
    service-url.defaultZone: http://service-user:password@${discovery-address}${infrastructure-context-path}/eureka/

legal-service:
  analytics:
    name: analytics-service
    credentials:
      user: service-user
      password: password
  hbaseIndexing:
    name: hbase-indexing-service
    credentials:
      user: service-user
      password: password
