####################
Service settings:
####################

service-port: 8350
discovery-address: localhost:8000
external-service-address: localhost:80
service-status-page-protocol: http://

####################
    