spring.application.name: legal-service

server.port: 8350

security:
  user:
    name: service-user 
    password: password 
    roles: USER 

legalService:
  analytics:
    name: analytics-service
    credentials:
      user: service-user
      password: password
  hbaseIndexing:
    name: hbase-indexing-service
    credentials:
      user: service-user
      password: password

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5    
    serviceUrl:
      defaultZone: http://service-user:password@localhost:8000/eureka
