spring.application.name: render-service

server.port: 8150

security:
  user:
    name: service-user 
    password: password 
    roles: USER 

renderService:
  hbaseIndexing:
    name: hbase-indexing-service
    credentials:
      user: service-user
      password: password

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5    
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
