discovery-address: localhost:8000
external-service-address: localhost:${server.port}

server:
  port: 8150
  max-http-header-size: 200000
  servlet.context-path: ${render-context-path}

spring:
  application.name: render-service
  security.user:
    name: service-user 
    password: password
    roles: USER

management:
  endpoints.web.exposure.include: "*" 
  endpoint.health.show-details: ALWAYS

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: ${render-context-path}/actuator/health
    status-page-url-path: http://service-user:password@${external-service-address}${render-context-path}/actuator/info
    management.context-path: ${render-context-path}
    metadata-map.user:
      name: service-user
      password: password
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5    
    service-url.defaultZone: http://service-user:password@${discovery-address}${infrastructure-context-path}/eureka/

render-service:
  hbaseIndexing:
    name: hbase-indexing-service
    credentials:
      user: service-user
      password: password
