/*
 * This file is generated by jOOQ.
 */
package net.thomas.portfolio.usage_data.schema.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import net.thomas.portfolio.usage_data.schema.tables.UserAccessedDocument;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserAccessedDocumentRecord extends TableRecordImpl<UserAccessedDocumentRecord> implements Record5<String, String, Integer, Integer, Timestamp> {

    private static final long serialVersionUID = 1829409878;

    /**
     * Setter for <code>user_accessed_document.document_type</code>.
     */
    public void setDocumentType(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>user_accessed_document.document_type</code>.
     */
    public String getDocumentType() {
        return (String) get(0);
    }

    /**
     * Setter for <code>user_accessed_document.document_uid</code>.
     */
    public void setDocumentUid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>user_accessed_document.document_uid</code>.
     */
    public String getDocumentUid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>user_accessed_document.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>user_accessed_document.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>user_accessed_document.access_type_id</code>.
     */
    public void setAccessTypeId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>user_accessed_document.access_type_id</code>.
     */
    public Integer getAccessTypeId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>user_accessed_document.time_of_access</code>.
     */
    public void setTimeOfAccess(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>user_accessed_document.time_of_access</code>.
     */
    public Timestamp getTimeOfAccess() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, Integer, Integer, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, Integer, Integer, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return UserAccessedDocument.USER_ACCESSED_DOCUMENT.DOCUMENT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return UserAccessedDocument.USER_ACCESSED_DOCUMENT.DOCUMENT_UID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return UserAccessedDocument.USER_ACCESSED_DOCUMENT.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return UserAccessedDocument.USER_ACCESSED_DOCUMENT.ACCESS_TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return UserAccessedDocument.USER_ACCESSED_DOCUMENT.TIME_OF_ACCESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getDocumentType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getDocumentUid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getAccessTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getTimeOfAccess();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getDocumentType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDocumentUid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getAccessTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getTimeOfAccess();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAccessedDocumentRecord value1(String value) {
        setDocumentType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAccessedDocumentRecord value2(String value) {
        setDocumentUid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAccessedDocumentRecord value3(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAccessedDocumentRecord value4(Integer value) {
        setAccessTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAccessedDocumentRecord value5(Timestamp value) {
        setTimeOfAccess(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAccessedDocumentRecord values(String value1, String value2, Integer value3, Integer value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserAccessedDocumentRecord
     */
    public UserAccessedDocumentRecord() {
        super(UserAccessedDocument.USER_ACCESSED_DOCUMENT);
    }

    /**
     * Create a detached, initialised UserAccessedDocumentRecord
     */
    public UserAccessedDocumentRecord(String documentType, String documentUid, Integer userId, Integer accessTypeId, Timestamp timeOfAccess) {
        super(UserAccessedDocument.USER_ACCESSED_DOCUMENT);

        set(0, documentType);
        set(1, documentUid);
        set(2, userId);
        set(3, accessTypeId);
        set(4, timeOfAccess);
    }
}
