server.port: 8300

spring:
  application:
    name: analytics-service
  security:
    user:
      name: service-user 
      password: password 
      roles: USER 

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registryFetchIntervalSeconds: 5    
    service-url:
      defaultZone: http://service-user:password@localhost:8000/Infrastructure/eureka/

analytics-service:
  hbaseIndexing:
    name: hbase-indexing-service
    credentials:
      user: service-user
      password: password
