discovery-address: localhost:8000
external-service-address: localhost:${server.port}

server:
  port: 8300
  max-http-header-size: 200000

  servlet.context-path: ${analytics-context-path}

spring:
  application.name: analytics-service
  security.user:
    name: service-user 
    password: password
    roles: USER

management:
  endpoints.web.exposure.include: "*" 
  endpoint.health.show-details: ALWAYS

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: ${analytics-context-path}/actuator/health
    status-page-url-path: http://service-user:password@${external-service-address}${analytics-context-path}/actuator/health
    management.context-path: ${analytics-context-path}/actuator
    metadata-map.user:
      name: service-user
      password: password
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5    
    service-url.defaultZone: http://service-user:password@${discovery-address}${infrastructure-context-path}/eureka/

analytics-service:
  hbaseIndexing:
    name: hbase-indexing-service
    credentials:
      user: service-user
      password: password