/*
 * This file is generated by jOOQ.
*/
package net.usage_data.schema;


import javax.annotation.Generated;

import net.usage_data.schema.tables.AccessType;
import net.usage_data.schema.tables.User;
import net.usage_data.schema.tables.UserAccessedDocument;


/**
 * Convenience access to all tables in usage_activity
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>usage_activity.access_type</code>.
     */
    public static final AccessType ACCESS_TYPE = net.usage_data.schema.tables.AccessType.ACCESS_TYPE;

    /**
     * The table <code>usage_activity.user</code>.
     */
    public static final User USER = net.usage_data.schema.tables.User.USER;

    /**
     * The table <code>usage_activity.user_accessed_document</code>.
     */
    public static final UserAccessedDocument USER_ACCESSED_DOCUMENT = net.usage_data.schema.tables.UserAccessedDocument.USER_ACCESSED_DOCUMENT;
}
