####################
Service settings:
####################

service-port: 80
discovery-address: localhost:8000
external-service-address: localhost:80
external-protocol: http://

####################
