spring.application.name: sample-service

server.port: 8200

security:
  user:
    name: user 
    password: password 
    roles: USER 

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
#      defaultZone: http://ec2-34-209-142-238.us-west-2.compute.amazonaws.com:8000/
      defaultZone: http://localhost:8000/eureka
