spring.application.name: sample-service

server.port: 8100

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.0.13:8000/eureka/