spring.application.name: hbase-indexing-service
server.port: 8120

security:
  user:
    name: service-user 
    password: password
    roles: USER

hbaseIndexingService:
  randomSeed: 1234
  legal:
    name: legal-service
    credentials:
      user: service-user
      password: password
          
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
    