####################
Service settings:
####################

service-context-path: ${hbase-indexing-context-path}
service-port: 8120
service-name: ${hbase-indexing-service-name}
service-status-page: http://service-user:password@${external-service-address}${service-context-path}/v1/schema
discovery-address: localhost:8000
external-service-address: localhost:80

####################
Unique settings:
####################

http:
  mappers:
    jsonPrettyPrint: true

hbase-indexing-service:
  randomSeed: 1234 

####################
Standard settings:
####################

server:
  port: ${service-port}
  max-http-header-size: 200000
  servlet.context-path: ${service-context-path}
  
  tomcat:
    max-connections: 2000
    max-http-post-size: 200000
    max-threads: 50
    min-spare-threads: 10

spring:
  application.name: ${service-name}
  security.user:
    name: service-user 
    password: password
    roles: USER

management:
  endpoints.web:
    base-path: /actuator
    cors.allowed-origins: true
    exposure.include: "*" 
  endpoint.health.show-details: ALWAYS

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
    health-check-url-path: ${service-context-path}/actuator/health
    status-page-url-path: ${service-status-page}
    metadata-map:
      management.context-path: ${service-context-path}/actuator
      user:
        name: service-user
        password: password
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5    
    service-url.defaultZone: http://service-user:password@${discovery-address}${infrastructure-context-path}/eureka/

####################
  