spring.application.name: hbase-indexing-service
server.port: 8100

security:
  user:
    name: service-user 
    password: password
    roles: USER

hbaseIndexingService:
  randomSeed: 1234
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
#      defaultZone: http://ec2-34-209-142-238.us-west-2.compute.amazonaws.com:8000/
      defaultZone: http://localhost:8000/eureka
    