server.port: 8120

spring:
  application:
    name: hbase-indexing-service
  security:
    user:
      name: service-user 
      password: password
      roles: USER

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registryFetchIntervalSeconds: 5    
    service-url:
      defaultZone: http://service-user:password@localhost:8000/Infrastructure/eureka/

http:
  mappers:
    jsonPrettyPrint: true

hbase-indexing-service:
  randomSeed: 1234
          
    