/*
 * This file is generated by jOOQ.
 */
package net.thomas.portfolio.usage_data.schema;


import javax.annotation.Generated;

import net.thomas.portfolio.usage_data.schema.tables.AccessType;
import net.thomas.portfolio.usage_data.schema.tables.User;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index SQLITE_AUTOINDEX_ACCESS_TYPE_1 = Indexes0.SQLITE_AUTOINDEX_ACCESS_TYPE_1;
    public static final Index SQLITE_AUTOINDEX_USER_1 = Indexes0.SQLITE_AUTOINDEX_USER_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index SQLITE_AUTOINDEX_ACCESS_TYPE_1 = Internal.createIndex("sqlite_autoindex_access_type_1", AccessType.ACCESS_TYPE, new OrderField[] { AccessType.ACCESS_TYPE.NAME }, true);
        public static Index SQLITE_AUTOINDEX_USER_1 = Internal.createIndex("sqlite_autoindex_user_1", User.USER, new OrderField[] { User.USER.NAME }, true);
    }
}
