/*
 * This file is generated by jOOQ.
 */
package net.thomas.portfolio.usage_data.schema;


import javax.annotation.Generated;

import net.thomas.portfolio.usage_data.schema.tables.AccessType;
import net.thomas.portfolio.usage_data.schema.tables.SqliteSequence;
import net.thomas.portfolio.usage_data.schema.tables.User;
import net.thomas.portfolio.usage_data.schema.tables.UserAccessedDocument;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>access_type</code>.
     */
    public static final AccessType ACCESS_TYPE = net.thomas.portfolio.usage_data.schema.tables.AccessType.ACCESS_TYPE;

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public static final SqliteSequence SQLITE_SEQUENCE = net.thomas.portfolio.usage_data.schema.tables.SqliteSequence.SQLITE_SEQUENCE;

    /**
     * The table <code>user</code>.
     */
    public static final User USER = net.thomas.portfolio.usage_data.schema.tables.User.USER;

    /**
     * The table <code>user_accessed_document</code>.
     */
    public static final UserAccessedDocument USER_ACCESSED_DOCUMENT = net.thomas.portfolio.usage_data.schema.tables.UserAccessedDocument.USER_ACCESSED_DOCUMENT;
}
