package net.thomas.portfolio.hbase_index.schema;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;

import net.thomas.portfolio.hbase_index.schema.processing.Entity2DataTypeConverterUnitTest;
import net.thomas.portfolio.hbase_index.schema.processing.visitor.VisitorTestSuite;

@RunWith(Suite.class)
@Suite.SuiteClasses({ AutoGeneratedEntityMethodsUnitTest.class, EventProtocolUnitTest.class, Entity2DataTypeConverterUnitTest.class, VisitorTestSuite.class })
public class SchemaTestSuite {
}