spring.application.name: usage-data-service
server.port: 8150

security:
  user:
    name: service-user 
    password: password
    roles: USER
     
usageDataService:
  database:
    host: localhost
    port: 3306
    schema: usage_data
    user: root
    password: computer
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
#      defaultZone: http://ec2-34-209-142-238.us-west-2.compute.amazonaws.com:8000/
      defaultZone: http://localhost:8000/eureka
    