server.port: 8200

spring:
  application:
    name: usage-data-service
  security:
    user:
      name: service-user 
      password: password
      roles: USER

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registryFetchIntervalSeconds: 5    
    service-url:
      defaultZone: http://service-user:password@localhost:8000/Infrastructure/eureka/
     
usage-data-service:
  hbaseIndexing:
    name: hbase-indexing-service
    credentials:
      user: service-user
      password: password
  database:
    host: localhost
    port: 3306
    schema: usage_data
    user: root
    password: computer
    