spring.application.name: nexus-service

security:
  user:
    name: service-user 
    password: password 
    roles: USER 

server:
  port: 8100
  max-http-header-size: 200000
  
  tomcat:
    max-connections: 2000
    max-http-post-size: 200000
    max-threads: 50
    min-spare-threads: 10
    
nexusService:
  analytics:
    name: analytics-service
    credentials:
      user: service-user
      password: password
  hbaseIndexing:
    name: hbase-indexing-service
    credentials:
      user: service-user
      password: password
  legal:
    name: legal-service
    credentials:
      user: service-user
      password: password
  rendering:
    name: render-service
    credentials:
      user: service-user
      password: password
  usage:
    name: usage-data-service
    credentials:
      user: service-user
      password: password
    
logging:
  level:
    org:
      springframework: INFO
    springfox: INFO

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5    
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
