discovery-address: localhost:8000
external-service-address: localhost:${server.port}

server:
  port: 8100
  max-http-header-size: 200000
  #servlet.path: ${nexus-context-path}
  servlet.context-path: ${nexus-context-path}
  
  tomcat:
    max-connections: 2000
    max-http-post-size: 200000
    max-threads: 50
    min-spare-threads: 10

spring:
  application.name: nexus-service
  security.user:
    name: service-user 
    password: password
    roles: USER

graphiql.endpoint: ${nexus-context-path}/graphql

management:
  endpoints:
    web:
      base-path: /actuator
      cors.allowed-origins: true
      exposure.include: "*"
    jmx:
      exposure.include: "*"
  endpoint.health.show-details: ALWAYS

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: ${nexus-context-path}/actuator/health
    status-page-url-path: http://${external-service-address}${nexus-context-path}/graphiql
    management.context-path: ${nexus-context-path}/actuator
    metadata-map.user:
      name: service-user
      password: password
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5    
    service-url.defaultZone: http://service-user:password@${discovery-address}${infrastructure-context-path}/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
      circuitBreaker:
        requestVolumeThreshold: 5
        sleepWindowInMilliseconds: 1000
      metrics:
        rollingStats:
          timeInMilliseconds: 600000
          numBuckets: 600

nexus-service:
  analytics:
    name: analytics-service
    credentials:
      user: service-user
      password: password
  hbaseIndexing:
    name: hbase-indexing-service
    credentials:
      user: service-user
      password: password
  legal:
    name: legal-service
    credentials:
      user: service-user
      password: password
  rendering:
    name: render-service
    credentials:
      user: service-user
      password: password
  usage:
    name: usage-data-service
    credentials:
      user: service-user
      password: password
    
logging:
  level:
    org:
      springframework: INFO
    springfox: INFO
