server:
  port: 8100
  max-http-header-size: 200000
  
  tomcat:
    max-connections: 2000
    max-http-post-size: 200000
    max-threads: 50
    min-spare-threads: 10

management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      cors:
        allowed-origins: true
      exposure:
        include: hystrix.stream, info, health

spring:
  application:
    name: nexus-service
  security:
    user:
      name: service-user 
      password: password 
      roles: USER 


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registryFetchIntervalSeconds: 5    
    service-url:
      defaultZone: http://service-user:password@localhost:8000/Infrastructure/eureka/
    
nexus-service:
  analytics:
    name: analytics-service
    credentials:
      user: service-user
      password: password
  hbaseIndexing:
    name: hbase-indexing-service
    credentials:
      user: service-user
      password: password
  legal:
    name: legal-service
    credentials:
      user: service-user
      password: password
  rendering:
    name: render-service
    credentials:
      user: service-user
      password: password
  usage:
    name: usage-data-service
    credentials:
      user: service-user
      password: password
    
logging:
  level:
    org:
      springframework: INFO
    springfox: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
      circuitBreaker:
        requestVolumeThreshold: 5
        sleepWindowInMilliseconds: 1000
      metrics:
        rollingStats:
          timeInMilliseconds: 600000
          numBuckets: 600
