spring.application.name: nexus-service

security:
  user:
    name: user 
    password: password 
    roles: USER 

server:
  port: 8100
  
  tomcat:
    max-connections: 2000
    max-http-header-size: 120000
    max-http-post-size: 120000
    max-threads: 50
    min-spare-threads: 10
    
nexusService:
  hbaseIndexing:
    name: hbase-indexing-service
    credentials:
      user: service-user
      password: password
    
logging:
  level:
    org:
      springframework: INFO
    springfox: INFO

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
#      defaultZone: http://ec2-34-209-142-238.us-west-2.compute.amazonaws.com:8000/
      defaultZone: http://localhost:8000/eureka
