/*
 * This file is generated by jOOQ.
 */
package net.thomas.portfolio.usage_data.schema.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import net.thomas.portfolio.usage_data.schema.DefaultSchema;
import net.thomas.portfolio.usage_data.schema.Keys;
import net.thomas.portfolio.usage_data.schema.tables.records.UserAccessedDocumentRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserAccessedDocument extends TableImpl<UserAccessedDocumentRecord> {

    private static final long serialVersionUID = 1618396624;

    /**
     * The reference instance of <code>user_accessed_document</code>
     */
    public static final UserAccessedDocument USER_ACCESSED_DOCUMENT = new UserAccessedDocument();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserAccessedDocumentRecord> getRecordType() {
        return UserAccessedDocumentRecord.class;
    }

    /**
     * The column <code>user_accessed_document.document_type</code>.
     */
    public final TableField<UserAccessedDocumentRecord, String> DOCUMENT_TYPE = createField("document_type", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>user_accessed_document.document_uid</code>.
     */
    public final TableField<UserAccessedDocumentRecord, String> DOCUMENT_UID = createField("document_uid", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>user_accessed_document.user_id</code>.
     */
    public final TableField<UserAccessedDocumentRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>user_accessed_document.access_type_id</code>.
     */
    public final TableField<UserAccessedDocumentRecord, Integer> ACCESS_TYPE_ID = createField("access_type_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>user_accessed_document.time_of_access</code>.
     */
    public final TableField<UserAccessedDocumentRecord, Timestamp> TIME_OF_ACCESS = createField("time_of_access", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>user_accessed_document</code> table reference
     */
    public UserAccessedDocument() {
        this(DSL.name("user_accessed_document"), null);
    }

    /**
     * Create an aliased <code>user_accessed_document</code> table reference
     */
    public UserAccessedDocument(String alias) {
        this(DSL.name(alias), USER_ACCESSED_DOCUMENT);
    }

    /**
     * Create an aliased <code>user_accessed_document</code> table reference
     */
    public UserAccessedDocument(Name alias) {
        this(alias, USER_ACCESSED_DOCUMENT);
    }

    private UserAccessedDocument(Name alias, Table<UserAccessedDocumentRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserAccessedDocument(Name alias, Table<UserAccessedDocumentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> UserAccessedDocument(Table<O> child, ForeignKey<O, UserAccessedDocumentRecord> key) {
        super(child, key, USER_ACCESSED_DOCUMENT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<UserAccessedDocumentRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<UserAccessedDocumentRecord, ?>>asList(Keys.FK_USER_ACCESSED_DOCUMENT_USER_1, Keys.FK_USER_ACCESSED_DOCUMENT_ACCESS_TYPE_1);
    }

    public User user() {
        return new User(this, Keys.FK_USER_ACCESSED_DOCUMENT_USER_1);
    }

    public AccessType accessType() {
        return new AccessType(this, Keys.FK_USER_ACCESSED_DOCUMENT_ACCESS_TYPE_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAccessedDocument as(String alias) {
        return new UserAccessedDocument(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAccessedDocument as(Name alias) {
        return new UserAccessedDocument(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserAccessedDocument rename(String name) {
        return new UserAccessedDocument(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserAccessedDocument rename(Name name) {
        return new UserAccessedDocument(name, null);
    }
}
